esphome:
  name: bmv080-external-component

external_components:
  - source:
      type: local
      path: external

esp32:
  board: esp32dev
  framework:
    type: esp-idf

sensor:
  - platform: bmv080
    address: 0x54
    update_interval: 10s
    name: "Mein Test Sensor"

logger:
  level: DEBUG
  logs:
    component: DEBUG
    i2c: DEBUG

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 100kHz  # Langsamere I2C-Geschwindigkeit für Stabilität