esphome:
  name: bmv080-external-component
  platformio_options:
    board_build.f_cpu: 240000000L
    upload_speed: 115200
external_components:
    - source:
        type: local
        path: external

esp32:
  board: esp32dev
  framework:
    type: esp-idf

sensor:
  - platform: bmv080
    address: 0x54
    update_interval: 10s
    name: "Mein Test Sensor"
    
logger:

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true